version: '3.7'

services:
  croni:
    image: atareao/croni:latest
    restart: always
    init: true
    container_name: croni
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./crontab.txt:/crontab.txt:ro
    environment:
      - LOGLEVEL=debug
